#!/usr/bin/env python

from strands_tweets.srv import *
import rospy
from twython import Twython, TwythonError

class tweetsServer(object):
    def __init__(self):
        APP_KEY = rospy.get_param("/twitter/appKey")#'vDcKFy7YrG2NNvjvH0BTVQ'
        APP_SECRET = rospy.get_param("/twitter/appSecret")#'nDynC5hjYqBPW9xEEiULTG4FEHRTdCHTUVClHGu00'
        OAUTH_TOKEN = rospy.get_param("/twitter/oauthToken")#'2192647862-uGT366zFzOQgz0W0XoqqG6YIR9HFltYCWZDD07I'
        OAUTH_TOKEN_SECRET = rospy.get_param("/twitter/oauthTokenSecret")#'7ybaYLsFWhbTrRfFlxlIoxQX7SwiZbcmnidaOOgyc41nH'
        print APP_KEY, APP_SECRET, OAUTH_TOKEN, OAUTH_TOKEN_SECRET
        self._twitter = Twython(APP_KEY, APP_SECRET, OAUTH_TOKEN, OAUTH_TOKEN_SECRET)
        rospy.init_node('strands_tweets')
        self._tweet_srv = rospy.Service("/strands_tweets/Tweet",Tweet,self._tweet_srv_cb)
        print "Ready to Tweet."
        rospy.spin()

    def _tweet_srv_cb(self, req):
        print "Tweeting %s ..."%(req.text)
        try:
            self._twitter.update_status(status=req.text)
            result=True
        except TwythonError as e:
            print e
            result=False
        return TweetResponse(result)

if __name__ == '__main__':
    server = tweetsServer()


